meta_product_name: "Kter"
meta_title: "Kter - Established to help kitchen owners and restaurateurs navigate the food delivery market."
meta_description: "Established to help kitchen owners and restaurateurs navigate the food delivery market. Our goal is to increase revenue and value of real estate assets, and to provide restaurateurs with an easy access to an additional revenue stream once their business re-open."
meta_image: "logo.png" # should exist in `app/assets/images/`